### ISSUE TITLE
Feature request: Allow to add stroke color to the SVG

### ISSUE THREAD

**Issue by DannyFeliz** [biigpongsatorn/vue-svg-filler#5]
For example, I need to add a green stroke.

![loop-stroke-to-path](https://user-images.githubusercontent.com/5460365/41957357-b15a7be2-79b4-11e8-9852-a1a4dbe9139d.png)

**Comment by biigpongsatorn** [comment]
![image](https://user-images.githubusercontent.com/10693658/41960936-3c4fd632-7a1b-11e8-8049-f1b0898a4130.png)

I added 2 new props `stroke` and `hover-stroke-color`, Please update version to `1.0.4`

See example in https://biigpongsatorn.github.io/#/vue-svg-filler
