### ISSUE TITLE
Can the SVG be dynamically swapped out?

### ISSUE THREAD

**Issue by TamaEaston** [biigpongsatorn/vue-svg-filler#6]
Thank you for your work on this component, it's very useful.

I have a Vue project where I'd like to swap out a SVG, but keep the element (with a unique ID).

Is that possible through vue-svg-filler?

**Comment by biigpongsatorn** [comment]
@TamaEaston Now I don't understand much about your problem but I think you can use it.

Can you explain more detail about your problem or show your code ?

**Comment by TamaEaston** [comment]
@biigpongsatorn - thank you for the quick response, I'll try to explain.

Here's a simple example of what I'm thinking of. Say I have data with a number of SVG paths:

```
data: function() {
  return  {
  svgIcons: [   
   'static/svgs/file1.svg',
   'static/svgs/file2.svg',
   'static/svgs/file3.svg',
   'static/svgs/file4.svg'
  ]}
}
```

And I have a svg-filler element with an id:

```<svg-filler id="svg">```

Can I dynamically add or change the path of the svg-filler from the svgIcons data?

**Comment by biigpongsatorn** [comment]
@TamaEaston Thanks for your explain. 
The old version it's not support programmatic path change.
But now I published new version for support your case in version `1.0.6`.
And you can see example code in [https://jsfiddle.net/50wL7mdz/661191/](https://jsfiddle.net/50wL7mdz/661191/).

**Comment by biigpongsatorn** [comment]
@TamaEaston Can I close this issue ?

**Comment by TamaEaston** [comment]
@biigpongsatorn - it works like a charm! Thank you for adding that functionality. Please close this issue.

**Comment by biigpongsatorn** [comment]
@TamaEaston My pleasure. 🙂
